# Generated by Django 5.2.11 on 2026-02-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255, unique=True)),
                ('required_skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='is_cached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='resume_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
