# Generated by Django 5.2.11 on 2026-02-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_roleskill_resumeanalysis_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='role_profile_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roleskill',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roleskill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roleskill',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
