# Generated by Django 5.2.11 on 2026-03-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resumeanalysis_role_profile_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMarketBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, unique=True)),
                ('core_skills', models.JSONField()),
                ('advanced_skills', models.JSONField()),
                ('experience_expectation', models.TextField()),
                ('project_expectation', models.TextField()),
                ('version', models.CharField(default='v1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
