# Generated by Django 5.2.11 on 2026-03-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_rolemarketbenchmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=100)),
                ('role_match_data', models.JSONField()),
                ('improvement_plan', models.JSONField()),
                ('dashboard_summary', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='is_cached',
        ),
        migrations.AddField(
            model_name='rolemarketbenchmark',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
